spring:
  datasource:
    url: jdbc:mysql://thoughthub-db:3306/thoughthub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: #yourpassword
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
